import csv
from pathlib import Path

HTML_TEMPLATE = """
<table border="1" style="border-collapse: collapse; width: 100%;">
    <thead>
        <tr>{headers}</tr>
    </thead>
    <tbody>
        {rows}
    </tbody>
</table>
"""

if __name__ == "__main__":
    base = Path(__file__).parent.parent
    input_csv = base / "docs" / "master_report.csv" # Generated by script #19
    output_html = base / "docs" / "data_table.html"
    
    try:
        with open(input_csv, 'r') as f:
            reader = csv.reader(f)
            header_row = next(reader)
            
            headers = "".join(f"<th>{h}</th>" for h in header_row)
            rows = ""
            for row in reader:
                rows += "<tr>" + "".join(f"<td>{cell}</td>" for cell in row) + "</tr>\n"
                
        output_html.write_text(HTML_TEMPLATE.format(headers=headers, rows=rows))
        print(f"✅ HTML table generated at {output_html.name}")
    except FileNotFoundError:
        print("❌ master_report.csv not found. Run merge_master_report.py first.")
